# Generated by Django 4.1.5 on 2023-01-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.TextField(max_length=100, null=True)),
                ('dateIn', models.DateField(max_length=100, null=True)),
                ('dateOut', models.DateField(max_length=100, null=True)),
                ('Stats', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
