# Generated by Django 4.1.5 on 2023-01-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='idnum',
            field=models.TextField(max_length=15, null=True),
        ),
    ]
